AntBulletEnv-v0:
  total_timesteps: 2_000_000
  normalize_kwargs: >
    dict(norm_obs=True, norm_reward=False)
  batch_size: 128
  clip_range: 0.4
  ent_coef: 0.0
  env_wrapper: sb3_contrib.common.wrappers.TimeFeatureWrapper
  gae_lambda: 0.9
  gamma: 0.99
  learning_rate: 3e-05
  max_grad_norm: 0.5
  n_envs: 16
  n_epochs: 20
  n_steps: 512
  normalize: True
  policy: "src.custom_policy.TransformerPolicy"
  policy_kwargs: >
    dict(
      features_extractor_kwargs=dict(embed_dim=64, n_heads=2, n_layers=1, dropout=0.0),
      net_arch=[dict(pi=[256, 256], vf=[256, 256])]
    )
  sde_sample_freq: 4
  use_sde: true
  vf_coef: 0.5